-- 06_inventory.sql - Populate inventory levels
USE gap_retail_db;

SET FOREIGN_KEY_CHECKS=0;
START TRANSACTION;
ALTER TABLE inventory_levels AUTO_INCREMENT = 1;

-- Warehouse inventory - East Coast
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate)
VALUES
-- Northeast Distribution Center (ID: 1)
(1, 'GAP-TS-LG-WHT-S', 1, NULL, 'Warehouse', 50, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 20, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(2, 'GAP-TS-LG-WHT-M', 1, NULL, 'Warehouse', 65, 0, NULL, 3, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 20, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(3, 'GAP-TS-LG-WHT-L', 1, NULL, 'Warehouse', 60, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 20, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(4, 'GAP-TS-LG-NVY-S', 1, NULL, 'Warehouse', 40, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 15, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(5, 'GAP-TS-LG-NVY-M', 1, NULL, 'Warehouse', 50, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 15, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(6, 'GAP-TS-LG-NVY-L', 1, NULL, 'Warehouse', 45, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 15, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(77, 'GAP-BL-FL-WHT-XS', 1, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(78, 'GAP-BL-FL-WHT-S', 1, NULL, 'Warehouse', 35, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(79, 'GAP-BL-FL-WHT-M', 1, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY));

-- Mid-Atlantic Fulfillment Center (ID: 2)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate)
VALUES
(7, 'GAP-JN-VW-LTBLU-30', 2, NULL, 'Warehouse', 35, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(8, 'GAP-JN-VW-LTBLU-32', 2, NULL, 'Warehouse', 40, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(9, 'GAP-JN-VW-LTBLU-34', 2, NULL, 'Warehouse', 38, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(10, 'GAP-JN-VW-MDMBLU-30', 2, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(11, 'GAP-JN-VW-MDMBLU-32', 2, NULL, 'Warehouse', 36, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(12, 'GAP-JN-VW-MDMBLU-34', 2, NULL, 'Warehouse', 35, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(83, 'GAP-JN-HR-DKBLU-25', 2, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(84, 'GAP-JN-HR-DKBLU-27', 2, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(85, 'GAP-JN-HR-DKBLU-29', 2, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY));

-- Southeast Regional Hub (ID: 3)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate)
VALUES
(13, 'GAP-JK-PF-BLK-S', 3, NULL, 'Warehouse', 25, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(14, 'GAP-JK-PF-BLK-M', 3, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(15, 'GAP-JK-PF-NVY-S', 3, NULL, 'Warehouse', 22, 0, NULL, 0, NULL, 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(16, 'GAP-JK-PF-NVY-M', 3, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(89, 'GAP-DR-PS-BLK-XS', 3, NULL, 'Warehouse', 20, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(90, 'GAP-DR-PS-BLK-S', 3, NULL, 'Warehouse', 25, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(91, 'GAP-DR-PS-BLU-XS', 3, NULL, 'Warehouse', 18, 0, NULL, 0, NULL, 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(92, 'GAP-DR-PS-BLU-S', 3, NULL, 'Warehouse', 22, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY));

-- Midwest Distribution Facility (ID: 4)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate)
VALUES
(17, 'GAP-SH-PS-GRY-S', 4, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(18, 'GAP-SH-PS-GRY-M', 4, NULL, 'Warehouse', 38, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(19, 'GAP-SH-PS-BLK-S', 4, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(20, 'GAP-SH-PS-BLK-M', 4, NULL, 'Warehouse', 40, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(93, 'GAP-KT-GR-BLU-4T', 4, NULL, 'Warehouse', 35, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(94, 'GAP-KT-GR-BLU-5T', 4, NULL, 'Warehouse', 38, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(95, 'GAP-KT-GR-RED-4T', 4, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(96, 'GAP-KT-GR-RED-5T', 4, NULL, 'Warehouse', 35, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY));

-- Southwest Fulfillment Center (ID: 5)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate)
VALUES
(21, 'GAP-HD-OC-GRY-S', 5, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(22, 'GAP-HD-OC-GRY-M', 5, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(23, 'GAP-HD-OC-GRY-L', 5, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(24, 'GAP-HD-OC-BLK-S', 5, NULL, 'Warehouse', 25, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(25, 'GAP-HD-OC-BLK-M', 5, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(26, 'GAP-HD-OC-BLK-L', 5, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(97, 'GAP-BO-OS-WHT-0M3M', 5, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(98, 'GAP-BO-OS-WHT-3M6M', 5, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(99, 'GAP-BO-OS-WHT-6M9M', 5, NULL, 'Warehouse', 25, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY));

-- Northwest Distribution Hub (ID: 6)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate)
VALUES
(27, 'GAP-CH-SF-KHK-30', 6, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(28, 'GAP-CH-SF-KHK-32', 6, NULL, 'Warehouse', 35, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(29, 'GAP-CH-SF-KHK-34', 6, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(30, 'GAP-CH-SF-NVY-30', 6, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(31, 'GAP-CH-SF-NVY-32', 6, NULL, 'Warehouse', 32, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(32, 'GAP-CH-SF-NVY-34', 6, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(100, 'GAP-HM-BD-GRY-TWN', 6, NULL, 'Warehouse', 18, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(101, 'GAP-HM-BD-GRY-QN', 6, NULL, 'Warehouse', 20, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(102, 'GAP-HM-BD-WHT-TWN', 6, NULL, 'Warehouse', 16, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY));

-- West Coast Primary Center (ID: 7)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate)
VALUES
(33, 'GAP-FL-RP-GRN-S', 7, NULL, 'Warehouse', 24, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(34, 'GAP-FL-RP-GRN-M', 7, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(35, 'GAP-FL-RP-GRY-S', 7, NULL, 'Warehouse', 22, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(36, 'GAP-FL-RP-GRY-M', 7, NULL, 'Warehouse', 26, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(103, 'GAP-AC-CP-NVY-OS', 7, NULL, 'Warehouse', 25, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(104, 'GAP-AC-CP-BLK-OS', 7, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(105, 'GAP-AC-BL-BRN-32', 7, NULL, 'Warehouse', 18, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(106, 'GAP-AC-BL-BRN-34', 7, NULL, 'Warehouse', 20, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(107, 'GAP-AC-BL-BRN-36', 7, NULL, 'Warehouse', 15, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY));