-- 06_inventory.sql - Populate inventory levels
USE gap_retail_db;

SET FOREIGN_KEY_CHECKS=0;
START TRANSACTION;
ALTER TABLE inventory_levels AUTO_INCREMENT = 1;

-- Warehouse inventory - East Coast
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
-- Northeast Distribution Center (ID: 1)
(1, 'GAP-TS-LG-WHT-S', 1, NULL, 'Warehouse', 50, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 20, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(2, 'GAP-TS-LG-WHT-M', 1, NULL, 'Warehouse', 65, 0, NULL, 3, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 20, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(3, 'GAP-TS-LG-WHT-L', 1, NULL, 'Warehouse', 60, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 20, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(4, 'GAP-TS-LG-NVY-S', 1, NULL, 'Warehouse', 40, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 15, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(5, 'GAP-TS-LG-NVY-M', 1, NULL, 'Warehouse', 50, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 15, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(6, 'GAP-TS-LG-NVY-L', 1, NULL, 'Warehouse', 45, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 15, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(77, 'GAP-BL-FL-WHT-XS', 1, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(78, 'GAP-BL-FL-WHT-S', 1, NULL, 'Warehouse', 35, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(79, 'GAP-BL-FL-WHT-M', 1, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY));

-- Mid-Atlantic Fulfillment Center (ID: 2)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(7, 'GAP-JN-VW-LTBLU-30', 2, NULL, 'Warehouse', 35, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(8, 'GAP-JN-VW-LTBLU-32', 2, NULL, 'Warehouse', 40, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(9, 'GAP-JN-VW-LTBLU-34', 2, NULL, 'Warehouse', 38, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(10, 'GAP-JN-VW-MDMBLU-30', 2, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(11, 'GAP-JN-VW-MDMBLU-32', 2, NULL, 'Warehouse', 36, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(12, 'GAP-JN-VW-MDMBLU-34', 2, NULL, 'Warehouse', 35, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(83, 'GAP-JN-HR-DKBLU-25', 2, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(84, 'GAP-JN-HR-DKBLU-27', 2, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(85, 'GAP-JN-HR-DKBLU-29', 2, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY));

-- Southeast Regional Hub (ID: 3)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(13, 'GAP-JK-PF-BLK-S', 3, NULL, 'Warehouse', 25, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(14, 'GAP-JK-PF-BLK-M', 3, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(15, 'GAP-JK-PF-NVY-S', 3, NULL, 'Warehouse', 22, 0, NULL, 0, NULL, 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(16, 'GAP-JK-PF-NVY-M', 3, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(89, 'GAP-DR-PS-BLK-XS', 3, NULL, 'Warehouse', 20, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(90, 'GAP-DR-PS-BLK-S', 3, NULL, 'Warehouse', 25, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(91, 'GAP-DR-PS-BLU-XS', 3, NULL, 'Warehouse', 18, 0, NULL, 0, NULL, 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(92, 'GAP-DR-PS-BLU-S', 3, NULL, 'Warehouse', 22, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY));

-- Midwest Distribution Facility (ID: 4)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(17, 'GAP-SH-PS-GRY-S', 4, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(18, 'GAP-SH-PS-GRY-M', 4, NULL, 'Warehouse', 38, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(19, 'GAP-SH-PS-BLK-S', 4, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(20, 'GAP-SH-PS-BLK-M', 4, NULL, 'Warehouse', 40, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(93, 'GAP-KT-GR-BLU-4T', 4, NULL, 'Warehouse', 35, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(94, 'GAP-KT-GR-BLU-5T', 4, NULL, 'Warehouse', 38, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(95, 'GAP-KT-GR-RED-4T', 4, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(96, 'GAP-KT-GR-RED-5T', 4, NULL, 'Warehouse', 35, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY));

-- Southwest Fulfillment Center (ID: 5)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(21, 'GAP-HD-OC-GRY-S', 5, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(22, 'GAP-HD-OC-GRY-M', 5, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(23, 'GAP-HD-OC-GRY-L', 5, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(24, 'GAP-HD-OC-BLK-S', 5, NULL, 'Warehouse', 25, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(25, 'GAP-HD-OC-BLK-M', 5, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(26, 'GAP-HD-OC-BLK-L', 5, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(97, 'GAP-BO-OS-WHT-0M3M', 5, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(98, 'GAP-BO-OS-WHT-3M6M', 5, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(99, 'GAP-BO-OS-WHT-6M9M', 5, NULL, 'Warehouse', 25, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY));

-- Northwest Distribution Hub (ID: 6)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(27, 'GAP-CH-SF-KHK-30', 6, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(28, 'GAP-CH-SF-KHK-32', 6, NULL, 'Warehouse', 35, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(29, 'GAP-CH-SF-KHK-34', 6, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(30, 'GAP-CH-SF-NVY-30', 6, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(31, 'GAP-CH-SF-NVY-32', 6, NULL, 'Warehouse', 32, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(32, 'GAP-CH-SF-NVY-34', 6, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(100, 'GAP-HM-BD-GRY-TWN', 6, NULL, 'Warehouse', 18, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(101, 'GAP-HM-BD-GRY-QN', 6, NULL, 'Warehouse', 20, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(102, 'GAP-HM-BD-WHT-TWN', 6, NULL, 'Warehouse', 16, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY));

-- West Coast Primary Center (ID: 7)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(33, 'GAP-FL-RP-GRN-S', 7, NULL, 'Warehouse', 24, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(34, 'GAP-FL-RP-GRN-M', 7, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(35, 'GAP-FL-RP-GRY-S', 7, NULL, 'Warehouse', 22, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(36, 'GAP-FL-RP-GRY-M', 7, NULL, 'Warehouse', 26, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(103, 'GAP-AC-CP-NVY-OS', 7, NULL, 'Warehouse', 25, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(104, 'GAP-AC-CP-BLK-OS', 7, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(105, 'GAP-AC-BL-BRN-32', 7, NULL, 'Warehouse', 18, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(106, 'GAP-AC-BL-BRN-34', 7, NULL, 'Warehouse', 20, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(107, 'GAP-AC-BL-BRN-36', 7, NULL, 'Warehouse', 15, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY));

-- Store inventory
-- GAP 5th Avenue Flagship (ID: 1)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(1, 'GAP-TS-LG-WHT-S', NULL, 1, 'Store', 15, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(2, 'GAP-TS-LG-WHT-M', NULL, 1, 'Store', 18, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(3, 'GAP-TS-LG-WHT-L', NULL, 1, 'Store', 16, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(4, 'GAP-TS-LG-NVY-S', NULL, 1, 'Store', 12, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(5, 'GAP-TS-LG-NVY-M', NULL, 1, 'Store', 15, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(6, 'GAP-TS-LG-NVY-L', NULL, 1, 'Store', 14, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(77, 'GAP-BL-FL-WHT-XS', NULL, 1, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(78, 'GAP-BL-FL-WHT-S', NULL, 1, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(79, 'GAP-BL-FL-WHT-M', NULL, 1, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(83, 'GAP-JN-HR-DKBLU-25', NULL, 1, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(84, 'GAP-JN-HR-DKBLU-27', NULL, 1, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(85, 'GAP-JN-HR-DKBLU-29', NULL, 1, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY));

-- GAP Times Square (ID: 2)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(7, 'GAP-JN-VW-LTBLU-30', NULL, 2, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(8, 'GAP-JN-VW-LTBLU-32', NULL, 2, 'Store', 12, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(9, 'GAP-JN-VW-LTBLU-34', NULL, 2, 'Store', 11, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(10, 'GAP-JN-VW-MDMBLU-30', NULL, 2, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(11, 'GAP-JN-VW-MDMBLU-32', NULL, 2, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(12, 'GAP-JN-VW-MDMBLU-34', NULL, 2, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(103, 'GAP-AC-CP-NVY-OS', NULL, 2, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(104, 'GAP-AC-CP-BLK-OS', NULL, 2, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(108, 'GAP-AC-TB-NTL-OS', NULL, 2, 'Store', 12, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(109, 'GAP-AC-TB-BLK-OS', NULL, 2, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY));

-- GAP Beverly Center (ID: 4)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(13, 'GAP-JK-PF-BLK-S', NULL, 4, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(14, 'GAP-JK-PF-BLK-M', NULL, 4, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(15, 'GAP-JK-PF-NVY-S', NULL, 4, 'Store', 7, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(16, 'GAP-JK-PF-NVY-M', NULL, 4, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(89, 'GAP-DR-PS-BLK-XS', NULL, 4, 'Store', 7, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(90, 'GAP-DR-PS-BLK-S', NULL, 4, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(91, 'GAP-DR-PS-BLU-XS', NULL, 4, 'Store', 6, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(92, 'GAP-DR-PS-BLU-S', NULL, 4, 'Store', 7, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY));

-- GAP Grove (ID: 5)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(17, 'GAP-SH-PS-GRY-S', NULL, 5, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(18, 'GAP-SH-PS-GRY-M', NULL, 5, 'Store', 12, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(19, 'GAP-SH-PS-BLK-S', NULL, 5, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(20, 'GAP-SH-PS-BLK-M', NULL, 5, 'Store', 13, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(93, 'GAP-KT-GR-BLU-4T', NULL, 5, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(94, 'GAP-KT-GR-BLU-5T', NULL, 5, 'Store', 12, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(95, 'GAP-KT-GR-RED-4T', NULL, 5, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(96, 'GAP-KT-GR-RED-5T', NULL, 5, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY));

-- GAP Michigan Avenue (ID: 7)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(21, 'GAP-HD-OC-GRY-S', NULL, 7, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(22, 'GAP-HD-OC-GRY-M', NULL, 7, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(23, 'GAP-HD-OC-GRY-L', NULL, 7, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(24, 'GAP-HD-OC-BLK-S', NULL, 7, 'Store', 7, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(25, 'GAP-HD-OC-BLK-M', NULL, 7, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(26, 'GAP-HD-OC-BLK-L', NULL, 7, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(97, 'GAP-BO-OS-WHT-0M3M', NULL, 7, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(98, 'GAP-BO-OS-WHT-3M6M', NULL, 7, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(99, 'GAP-BO-OS-WHT-6M9M', NULL, 7, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY));

-- GAP Market Street (ID: 9)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(27, 'GAP-CH-SF-KHK-30', NULL, 9, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(28, 'GAP-CH-SF-KHK-32', NULL, 9, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(29, 'GAP-CH-SF-KHK-34', NULL, 9, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(30, 'GAP-CH-SF-NVY-30', NULL, 9, 'Store', 7, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(31, 'GAP-CH-SF-NVY-32', NULL, 9, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(32, 'GAP-CH-SF-NVY-34', NULL, 9, 'Store', 7, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(100, 'GAP-HM-BD-GRY-TWN', NULL, 9, 'Store', 5, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 2, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(101, 'GAP-HM-BD-GRY-QN', NULL, 9, 'Store', 6, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 2, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(102, 'GAP-HM-BD-WHT-TWN', NULL, 9, 'Store', 4, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 2, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY));

-- GAP Union Square (ID: 10)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(33, 'GAP-FL-RP-GRN-S', NULL, 10, 'Store', 7, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(34, 'GAP-FL-RP-GRN-M', NULL, 10, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(35, 'GAP-FL-RP-GRY-S', NULL, 10, 'Store', 6, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(36, 'GAP-FL-RP-GRY-M', NULL, 10, 'Store', 7, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(105, 'GAP-AC-BL-BRN-32', NULL, 10, 'Store', 5, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 2, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(106, 'GAP-AC-BL-BRN-34', NULL, 10, 'Store', 6, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 2, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(107, 'GAP-AC-BL-BRN-36', NULL, 10, 'Store', 5, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 2, 2, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(110, 'GAP-AC-NC-GLD-OS', NULL, 10, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY));

-- GAP Newbury (ID: 11)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(37, 'GAP-SH-OX-WHT-S', NULL, 11, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(38, 'GAP-SH-OX-WHT-M', NULL, 11, 'Store', 12, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(39, 'GAP-SH-OX-WHT-L', NULL, 11, 'Store', 11, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(40, 'GAP-SH-OX-LBL-S', NULL, 11, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(41, 'GAP-SH-OX-LBL-M', NULL, 11, 'Store', 11, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(42, 'GAP-SH-OX-LBL-L', NULL, 11, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(111, 'GAP-AC-SC-GRY-OS', NULL, 11, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(112, 'GAP-AC-SC-NVY-OS', NULL, 11, 'Store', 7, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(113, 'GAP-AC-SC-RED-OS', NULL, 11, 'Store', 6, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY));

-- GAP Lincoln Road (ID: 15)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(43, 'GAP-KH-SL-KHK-32', NULL, 15, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(44, 'GAP-KH-SL-KHK-34', NULL, 15, 'Store', 10, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(45, 'GAP-KH-SL-OLV-32', NULL, 15, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(46, 'GAP-KH-SL-OLV-34', NULL, 15, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(108, 'GAP-AC-TB-NTL-OS', NULL, 15, 'Store', 15, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(109, 'GAP-AC-TB-BLK-OS', NULL, 15, 'Store', 14, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 5, 5, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY));

-- GAP Lenox Square (ID: 17)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(47, 'GAP-VS-QT-NVY-S', NULL, 17, 'Store', 7, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(48, 'GAP-VS-QT-NVY-M', NULL, 17, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(49, 'GAP-VS-QT-OLV-S', NULL, 17, 'Store', 6, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(50, 'GAP-VS-QT-OLV-M', NULL, 17, 'Store', 7, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(80, 'GAP-BL-FL-BLU-XS', NULL, 17, 'Store', 7, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(81, 'GAP-BL-FL-BLU-S', NULL, 17, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(82, 'GAP-BL-FL-BLU-M', NULL, 17, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(86, 'GAP-JN-HR-BLK-25', NULL, 17, 'Store', 7, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(87, 'GAP-JN-HR-BLK-27', NULL, 17, 'Store', 9, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(88, 'GAP-JN-HR-BLK-29', NULL, 17, 'Store', 8, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY), 0, NULL, 3, 3, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY));

-- Additional inventory for West Coast Primary Center (ID: 7)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(51, 'GAP-TK-RB-WHT-XS', 7, NULL, 'Warehouse', 35, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 15, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(52, 'GAP-TK-RB-WHT-S', 7, NULL, 'Warehouse', 40, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 15, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(53, 'GAP-TK-RB-WHT-M', 7, NULL, 'Warehouse', 38, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 15, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(54, 'GAP-TK-RB-BLK-XS', 7, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 15, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(55, 'GAP-TK-RB-BLK-S', 7, NULL, 'Warehouse', 38, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 15, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(56, 'GAP-TK-RB-BLK-M', 7, NULL, 'Warehouse', 34, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 15, 15, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY));

-- Slim Fit Jeans at Southeast Regional Hub (ID: 3)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(57, 'GAP-JN-SF-DKBLU-30', 3, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(58, 'GAP-JN-SF-DKBLU-32', 3, NULL, 'Warehouse', 34, 0, NULL, 2, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(59, 'GAP-JN-SF-DKBLU-34', 3, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(60, 'GAP-JN-SF-BLK-30', 3, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(61, 'GAP-JN-SF-BLK-32', 3, NULL, 'Warehouse', 32, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(62, 'GAP-JN-SF-BLK-34', 3, NULL, 'Warehouse', 30, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY));

-- Windbreaker Jackets at Mid-Atlantic Fulfillment Center (ID: 2)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(63, 'GAP-JK-WB-RED-S', 2, NULL, 'Warehouse', 20, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(64, 'GAP-JK-WB-RED-M', 2, NULL, 'Warehouse', 25, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(65, 'GAP-JK-WB-BLU-S', 2, NULL, 'Warehouse', 18, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(66, 'GAP-JK-WB-BLU-M', 2, NULL, 'Warehouse', 22, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(67, 'GAP-JK-WB-BLK-S', 2, NULL, 'Warehouse', 24, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY)),
(68, 'GAP-JK-WB-BLK-M', 2, NULL, 'Warehouse', 28, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 8, 8, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY));

-- Athletic Shorts at Northwest Distribution Hub (ID: 6)
INSERT INTO inventory_levels (VariantID, SKU, WarehouseID, StoreID, LocationType, QuantityOnHand, ReservedForPickup, PickupReservationExpiry, ReservedQuantity, ReservationExpiry, ReorderPoint, LowStockThreshold, LastStockCheckDate) VALUES
(69, 'GAP-SH-AT-BLK-S', 6, NULL, 'Warehouse', 26, 0, NULL, 1, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY), 10, 10, DATE_